### ISSUE TITLE
weird link: very hard to create correct link

### ISSUE THREAD

**Issue by lewisl** [jonathanjanssens/hugo-casper3#12]
In the partial post-card.html, there is a link to test.com, which is some completely bogus site.

In the partial, this should be a link to the author's metadata or, better, to the author's list of posts.

It looks like this now: `<a href="https://test.com" class="static-avatar author-profile-image">{{- partial "icons/avatar.html" -}}</a>'.   Both components need to be replaced but that is devilishly hard.

the href should go to the author's list page:  something like \author\George.    \author\ could be a string literal, but it is very complex to catenate string literals with function results in go templates.

The partial for "icons/avatar.html" also doesn't make any sense.  It is a geometric svg.   It now looks like this:  ```<svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><g fill="none" fill-rule="evenodd"><path d="M3.513 18.998C4.749 15.504 8.082 13 12 ...more points..." fill="#FFF"/></g></svg>```

It needs to be a tiny rendering of the author's picture, based on the Ghost template casper.  It is beyond my go template and Hugo abilities to specify this even though I have a url to author_image in the front matter for the author metadata page.

I suppose it is futile to post here as this theme now seems to be unmaintained...

**Comment by jonathanjanssens** [comment]
The link to test.com should not have been there and has been removed, I do not believe this is a 'bogus' site, just a mistake that it was left in there.

Can you explain why having the default avatar in avatar.html doesn't make sense? I do not know of a requirement for Hugo themes to support author images etc. This theme was developed for a specific  project I was working on that did not require that functionality.

This project is MIT licensed so you are welcome to provide a pull request or fork this repo if you are not happy with it. There are also 24 forks of this repo that you may want to look at as they may provide the functionality you are looking for.

**Comment by lewisl** [comment]
Sounds good. I’ll look. I made some small changes for flexibility. It’s working well for me now.

- Lewis

On Feb 26, 2021, at 7:11 AM, Jonathan Janssens <notifications@github.com> wrote:

﻿

The link to test.com should not have been there and has been removed, I do not believe this is a 'bogus' site, just a mistake that it was left in there.

Can you explain why having the default avatar in avatar.html doesn't make sense? I do not know of a requirement for Hugo themes to support author images etc. This theme was developed for a specific project I was working on that did not require that functionality.

This project is MIT licensed so you are welcome to provide a pull request or fork this repo if you are not happy with it. There are also 24 forks of this repo that you may want to look at as they may provide the functionality you are looking for.
