### ISSUE TITLE
Shortcode {{< youtube >}} does not show video

### ISSUE THREAD

**Issue by nsunami** [jonathanjanssens/hugo-casper3#5]
I'm trying to use a shortcode for youtube `{{< youtube >}}` but I cannot see the video. It seems like the video is loaded somewhere, but the video is not showing up. If I put it on autoplay, I can hear the sound but without the image. Any way to fix or workaround this?

**Comment by jonathanjanssens** [comment]
Hi nsunami, 

Thanks for reporting this. It has been fixed in the latest version on master.

Test page here: https://hugocasper3-demo.jonathanjanssens.com/post/video-test/

Thanks
