### ISSUE TITLE
images in front matter do not show up in post-cards

### ISSUE THREAD

**Issue by lewisl** [jonathanjanssens/hugo-casper3#6]
The markdown of a post has this front matter:
```
---
title: Doing Business
date: 2019-02-01
categories: [“ride”]
author: lewis
draft: false
feature_image: conf.png
--- 
```
The markdown and the png file are in a directory with the name of the post: ```doing-business```.

The feature_image front matter requires the underscore. The image appears when the post is viewed individually. But, it does not appear in the post-card view on any page that lists multiple posts. Instead of the image, a light gray background swatch is displayed with the name of the post in darker gray as the foreground.  

The only difference I can see between my site and your demo is that I have the image in the same folder as the index.md, while you have all images linked from the static/image directory. Seems like that should not matter.

The demo also does not work: you have several posts with feature_images, but they do not appear as part of the post card.  Seems broken even though the gray swatches show that the correct part of the template is executing.

This works very differently than the Casper-two theme that really was a dead ringer for the Ghost theme Casper.

Hard to get it to work reverse-engineering the demo.

**Comment by jonathanjanssens** [comment]
If your image is in a directory called `doing-business` your `feature_image` will need to be `/doing-business/conf.png` - this isn't broken. 

If this is the casper 2 theme you are referring to - https://github.com/eueung/hugo-casper-two - the images seem work the same way. If you know of a better way to handle the images feel free to submit a PR.

**Comment by lewisl** [comment]
I am happy to try both of your suggestions for casper3 as you are its author.

Casper-two does not work as you say.  If an image referenced in front matter is in the same directory as the index.md, one simply refers to the file by name as

```
cover: myping.png
```

No parens, no path,

In your suggestion, shouldn’t it be:   ./doing-business/conf.png?

I’ll try both and report back.

Thanks for both suggestions.

**Comment by lewisl** [comment]
I could not get feature_image in the same directory as the text to work. Putting images in /static/images works.  (I note that some themes like /static/img, although this might be deprecated in later versions of Hugo.)  So, progress.

I cannot get an image to appear as background to the site title on the home page (default index.md). I note that the demo does not have a banner image so I wonder if it is even possible.

<unrelated comment>
It would be nice if the powers-that-be insisted on both directory standards and front matter field name standards (cover vs feature_image or banner, etc.). The front matter item names are arbitrary but the benefit of requiring consistent usage is that one could  switch themes with much of each theme (though unlikely to be all) working. This is certainly the case with (the unjustly reviled) Wordpress.  For wordpress.org themes (though not always 3rd party themes) one can switch themes with an expectation that much but not all will work. It might be said that this limits creativity and design variety.  Not sure such a claim, if made, would be valid. What such consistency provides is that a fundamental subset of theme definition works and outside of that subset, all sorts of things are possible.  It isn’t possible to have themes with completely non-overlapping capabilities be plug-and-play.  But, there is some degree of commonality across Hugo designs: there are posts; there can be a banner design (it can be absent, but that only entails ignoring config and front matter fields, not have divergent fields; there are authors, etc. This core is NOT all that is permitted--the more the merrier.  It is just beneficial as a practical matter that a core subset be consistent.  Makes life easier all the way around. No—it can’t be enforced on 3rd party themes, but it could be made a requirement of being included in the Hugo sponsored directory.  That is such an important benefit that if the subset made sense, most theme authors would say, “no biggee—I can do that…”.
</unrelated comment>

**Comment by lewisl** [comment]
In the layout header-background.html, I can replace the title with the logo using an image.

What I’d like is the image stretched to fit the header background with the title text over it.

Probably simple but I am pretty unfamiliar with go templates.

If you can point me to the correct layout to modify and the template code I’ll give it a go.

I’ll look back at Casper-two.  While it is very different (many, many layouts), it does image banners so I’ll see if I can put it into the simpler casper3 layouts.

**Comment by jonathanjanssens** [comment]
I have added a test post with the image in the post directory and it works when the full path to the image is provided.

https://hugocasper3-demo.jonathanjanssens.com/post/image-test/

https://github.com/jonathanjanssens/hugo-casper3-demo/commit/21054b7976c3b2a4e9ee5f2d5f93eeb7c7ea5aee

There may be a better way to handle this but I don't really have time to work on it right now, the way it is setup now is running well on several sites but if there is a more standard way to do it I would welcome a suggestion for when I get some time, or a PR.

**Comment by jonathanjanssens** [comment]
The latest version on master also fixes the issue with the homepage image not showing. You can set a feature_image on the _index.md to set this.

e.g https://github.com/jonathanjanssens/hugo-casper3-demo/commit/6e093b707d6fd619ea8c4ea788a5a879babd379e

**Comment by lewisl** [comment]
I downloaded rather than cloned.

Can I access as download or need to clone so I can specify your branch.

Tx.

**Comment by lewisl** [comment]
Took a look.

Not the same thing.  You are still using an images sub-directory within the post subdirectory.

For much of Hugo the following is meant to work (but clearly might be theme dependent):

/content/
post/
                                foo-post/
                                                index.md        # contains markdown text obviously including front matter referring to feature_image
                                                feature.png    # the markdown and the image are peers within the post directory
                                post-two/
                                                index.md
                                                feature.jpg
                                                big-monster.jpg    # an inline image within index.md

It’s not the end of the world so don’t worry about it, but the above is a valid Hugo way to organize content.  I’ve switched away from the old Casper-Two.  I preferred it, but I have Hugo SSG sites hanging off a top level menu of a Ghost blog, which uses Casper.  Your casper3 exactly matches the latest version of Ghost casper theme (by design, I’ll wager…!). So, the whole thing appears as one.  Eventually, I’ll switch a more of the Ghost subsites (implemented as tags) to Hugo.

There is a reason this matters, though it’s not life threatening.  I can easily do mobile markdown editing and create a sort self-contained folder of the whole post, which syncs to my host where the site lives.  Then I ssh to run /snap/bin/hugo…  If the images are in /static/images or foo-post/images I have more uploads/syncs.  But, in the end it’s personal preference.

Thanks for keeping after this.

**Comment by jonathanjanssens** [comment]
If you want to store the image in the root post directory, not in the images subdirectory just remove /images from the feature_image so instead of 

`feature_image = "/post/image-test/images/manja-vitolic-gKXKBY-C-Dk-unsplash.jpg" `

you would want

` feature_image = "/post/image-test/manja-vitolic-gKXKBY-C-Dk-unsplash.jpg" `

**Comment by lewisl** [comment]
This is old and all fixed.    So, am closing.
