### ISSUE TITLE
How do I add static pages?

### ISSUE THREAD

**Issue by lukebarone** [jonathanjanssens/hugo-casper3#7]
I have some canonical URLs I'd like to use for my web site, but they are not blog entries. How can I create a menu with the theme to point to these pages?

**Comment by jonathanjanssens** [comment]
Check out the menu config item in the demo theme repo. You can add any pages or links you want to the menu: https://github.com/jonathanjanssens/hugo-casper3-demo/blob/master/config.toml#L20
